Feature/edit book logic
boostcampwm-2024/iOS10-MemorialHouse pull request #113
Opened 2024-12-01 15:46 UTC by iceHood

## #️⃣ 연관된 이슈
- #72 
<br>

## ⏰ 작업 시간

|예상 시간|실제 걸린 시간|
|:-:|:-:|
|10|2n|

## 📝 작업 내용

- MediaAttachment구현
- Media, EditBook Usecase만들기
- Media, EditBook ViewModel만들기
- 뷰 초과 작성 방지
- text, media description 저장 구현
- Snapshot기반 media저장 로직 구현
- Attachment 지우기 절차 로직 구현
<br>

## 📸 스크린샷

![화면 기록 2024-12-02 오전 12 01 33](https://github.com/user-attachments/assets/a9070127-73a1-4ad3-9312-4c486ec3fea0)

<br>

## 📒 리뷰 노트

1. Snapshot기반으로 저장방식이 변경되었습니다!
  따라서 기존의 temp로 저장하는 것은 슬슬... 보내주어야..
변한게 좀 많군요.... 하하... 죄송합니다..

<br>

## ⚽️ 트러블 슈팅

너무 길어서? 그냥 노션링크로 올릴꼐요... 하하... 죄송합니다..

- https://www.notion.so/kyxxn/reloading-79f32dc5342f4b389dc32dfa83992ea4?pvs=4
- https://www.notion.so/kyxxn/Attachment-784d39dec7c34f698fd63219cf02825a?pvs=4
- https://www.notion.so/kyxxn/a8d455af87164a02aa5e4d79e5b3fc92?pvs=4
- https://www.notion.so/kyxxn/didSelect-673627e8ac1a4179963bf7b029996666?pvs=4
- https://www.notion.so/kyxxn/965bb35e84cf4535a4482930a5d309dc?pvs=4
- https://www.notion.so/kyxxn/Cell-c70ba70b937c4b56ae57fcfd04a52c4e?pvs=4

2024-12-01 16:01 UTC, iceHood commented on MemorialHouse/MHData/MHData/Repository/LocalMediaRepository.swift
>  // TODO: nil이라면 바로 error를 return하도록 수정
나중에 해도 될까요...하하하....ㅠ

2024-12-01 16:02 UTC, iceHood commented on MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMediaUseCase.swift
> +public struct DefaultPersistentlyStoreMediaUseCase: PersistentlyStoreMediaUseCase {
네이밍 뭔가 안떠올라서 대충하긴했는데 좋은 이름 추천받습니다..

2024-12-01 16:10 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHPolaroidPhotoView.swift
> +extension MHPolaroidPhotoView: @preconcurrency MediaAttachable {
이거는 Xcode가 붙이래서 붙인 preconcurrency..

2024-12-01 16:34 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +        textView.text = ""
cell reuse되기전에 청소했습니다.. 구독을 꼭 끊어야 합니다.. (deinit이 안돼서)

2024-12-01 17:04 UTC, yuncheol-AHN approved these changes
정현님 고생하셨습니다 ~!~!
짱짱짱

2024-12-01 17:57 UTC, k2645 requested changes
정현님.. 정말.. 저희 팀의 "기둥" 이십니다.. 🥹 경배하라 갓.정.현 ✨

궁금했던 부분들과 수정하면 좋을 것 같은 제 조그만 의견 남겨두었습니다 ! 

추가로 뭔가 FileManager부터 URL과 Data 로직은 똑같은데 매개변수때문에 함수가 2개로 늘어나는 느낌이 드네용.. url과 data를 옵셔널로 둘 다 한 번에 받는 방식으로 처리하는 것에 대해선 어떻게 생각하시나욥??

그리고 코멘트에도 달아뒀지만, protocol이나 class들은 짧더라도 소스파일 단위로 분리해주면 이후에 해당 객체의 위치를 찾기 더 수월할 것 같다는 생각입니당 ~

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMediaUseCase.swift
> +            return try await repository.read(media: media, from: bookID).get()
P3: 해당 Repository만 읽어오기를 read로 표현하고 있는데, 다른 repo들과 통일성을 위해 fetch로 네이밍을 바꾸는건 어떨까요??

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHDomain/MHDomain/UseCase/DefaultMediaUseCase.swift
> +    }
P2: 해당 부분도 temp 가 사라짐에 따라 없어져야될 부분인가요?? 그렇다면 TODO.. 남겨주시면 감사하겠숩니당..

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
P3: 이건 해당 VC 이름에 대한 코멘트인데, 다른곳들은 네이밍이 모두 `Edit-`, `Read-`와 같이 동사로 시작해서 해당 ViewController도 `CreateBookViewController`로 변경하면 어떨까요??

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
> +@preconcurrency import Combine
P1: Combine에 @preconcurrency가 붙은 이유가 무엇인가욥?? 해당 키워드가 붙게된 이유가 궁금합니다 !

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
> +        view.addSubview(addPageButton)
P3: 위 주석(161줄)은 삭제하면 좋을 것 같습니당

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
>          // publishButton
P3: 해당 주석도 마찬가지입니당 !

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
> +        editPageTableView.keyboardDismissMode = .onDrag
P3: 옹 해당 옵션은 드래그를 할 때 키보드가 내려간다는 뜻일까요?

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
> +                case .updateViewController(title: let title):
P3:
```suggestion
                case .updateViewController(let title):
```
이게 자연스러워 보입니당 !

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +                }
P3:
```suggestion
                guard let mediaAttachment = value as? MediaAttachment,
                      mediaAttachment.mediaDescription.id == media.id else { return }
                attachment = mediaAttachment
```

정말 별것 아니긴한데.. guard문을 쓰면 depth가 덜 들어가서 가독성이 높아지는 느낌..? 입니당 (굉장히 개인적인 의견..)

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +    }
P3: `saveContents()` 메서드는 아래 메서드들 내부에서 호출되는 것 같은데 그렇다면 위치가 아래 메서드들 하단에 위치하는게 가독성이 더 좋아질 것 같습니당

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +    }
P3: 해당 메서드는 textView 내부에서 media를 다른곳으로 드래그해서 옮길때..? 호출되는 메서드인건가요..??

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +        return textStorage.attributes(at: index, effectiveRange: nil)[.attachment] as? MediaAttachment
P111111: 임교수님의 강의가 시급합니다. 🚨🚨🚨

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachment.swift
> +    var cachedViewProvider: MediaAttachmentViewProvider?
P3: 캐싱도 .. 구현하신건가요..?

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/ViewModel/EditBookViewModel.swift
> +    }
P3: addPage를 보니 생각났는데 deletePage는 아직 구현이 안..된거겠죠..??

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+SnapshotImage.swift
> +    }
P3: 해당 image snapshot은 어디서 사용되는건가요?

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachment.swift
P2: 해당 소스파일 내부에 여러 protocol들과 class들이 함께 섞여있는데, 파일별로 분리해야 나중에 해당 class 혹은 protocol을 찾기가 수월해질 것 같습니당 !

2024-12-01 17:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachment.swift
> +class MediaAttachmentViewProvider: NSTextAttachmentViewProvider {
P2: 해당 class가 다른곳에 또 상속될 일이 있나용?? 없다면 final 키워드를 붙여줘도 좋을 것 같습니당

2024-12-01 22:59 UTC, iceHood commented on MemorialHouse/MHData/MHData/Repository/LocalMediaRepository.swift
> +    private let snapshotFileName = ".snapshot"
이제 사용이 안되서 없앨 예정입니당,,

2024-12-01 22:59 UTC, iceHood commented on MemorialHouse/MHData/MHData/Repository/LocalMediaRepository.swift
> +    }
편집뷰에서 수정완려/저장 버튼을 눌렀을 때 호출됩니다!

2024-12-01 23:02 UTC, iceHood commented on MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
> +        guard let fileManager = try? DIContainer.shared.resolve(MHFileManager.self) else { return }
맞다 바꾸는 것을 까먹었네요,, 수정하겠습니다!

2024-12-01 23:04 UTC, iceHood commented on MemorialHouse/MHData/MHData/LocalStorage/FileManager/MHFileManager.swift
> +            try data.write(to: dataPath, options: .atomic)
저장할 때 임시파일 만들었다가 저장이 완료되면 실제 파일로 바뀌는 옵션입니다!

2024-12-01 23:16 UTC, iceHood commented on MemorialHouse/MHData/MHData/LocalStorage/FileManager/MHFileManager.swift
> +        ).first?.appending(path: path)
urls(for:in:)메스드에서
for:은 저희가 찾고자 하는 디렉토리(폴더)입니다.
in:은 해당 디렉토리를 찾고자 하는 영역입니다.
맥을 기준으로 설명드리면 ~/Document라든지 ~/Downloads 등이 있는데, ~가 in:에 해당하고, Downloads, Document가 for:에 해당합니다., 즉, in은 영역(사용자 영역, 로컬 영역-가끔 "앱을 전체 사용자가 사용할 수 있게 하겠습니까?" 그런것 있죠?, 네트워크 영역-공유 폴더 등)을 나타내고, for:는 실제 디렉토리를 의미합니다.

저희는 ~/Document를 사용한다고 코딩해놓은 것입니다!

문서가 더 잘 설명되어있으니 한번 보셔도 좋을 것같아요!

[공식크문서](https://developer.apple.com/documentation/foundation/filemanager/1407726-urls)

2024-12-01 23:18 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
> +@preconcurrency import Combine
지워놓고 푸시를 안했네요 ㅋㅋㅋㅋ 바로 반영할께욤

2024-12-01 23:20 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
> +        editPageTableView.keyboardDismissMode = .onDrag
아 해놓고 위치를 안바꿨네요! 더 어울리는 곳으로 옮길께요,, 영현님 말씀이 맞습니다

2024-12-01 23:20 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditBookViewController.swift
> +                case .updateViewController(title: let title):
요상한 자동완성이.... 반영하겠읍니다!

2024-12-01 23:26 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +    }
맞습니다

![image](https://github.com/user-attachments/assets/13515e9b-9f94-472b-9ab2-aaa0f39328a6)

저거를 안해주면 위에처럼 뜨더라구요,,

2024-12-01 23:26 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +        return textStorage.attributes(at: index, effectiveRange: nil)[.attachment] as? MediaAttachment
교수님 정년퇴직하셨답니다,,

2024-12-01 23:27 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachment.swift
> +    var cachedViewProvider: MediaAttachmentViewProvider?
이름이 cached여서 그렇지 그냥 reuse 그런 의미입니다,,,핳

2024-12-01 23:29 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIView+SnapshotImage.swift
> +    }
위에서 드래그-드랍할 때 현재 뷰 상태를 캡쳐할 때 사용합니다!

2024-12-02 00:26 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +        return textStorage.attributes(at: index, effectiveRange: nil)[.attachment] as? MediaAttachment
하드코딩 멋있네요

2024-12-02 00:38 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +    }
생각해보니 ViewController가 saveContents라는 함수를 들고 있는 것이 어색해보이네요..
```swift
func textStorage(
        _ textStorage: NSTextStorage,
        didProcessEditing editedMask: NSTextStorage.EditActions,
        range editedRange: NSRange,
        changeInLength delta: Int
    )
```
해당 함수를 없애고 위의 함수의 맨 마지막으로 옮겼습니다.

2024-12-02 01:06 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/MediaAttachment.swift
DataSource빼고는 전부 분리했습니다!

2024-12-02 01:55 UTC, Kyxxn approved these changes
ㄹㅇㄹㅇ 우리 팀의 기둥
감사합니다 고생하셨어요 !!!

2024-12-02 03:09 UTC, k2645 approved these changes
좋습니당 ~~ 수고많으셨어요 👍

2024-12-02 03:15 UTC, merged