[draft] Feature/audioplayer
boostcampwm-2024/iOS10-MemorialHouse pull request #122
Opened 2024-12-02 17:29 UTC by yuncheol-AHN

## #️⃣ 연관된 이슈

<br>

## ⏰ 작업 시간

|예상 시간|실제 걸린 시간|
|:-:|:-:|
|||

## 📝 작업 내용

<br>

## 📸 스크린샷

<br>

## 📒 리뷰 노트

<br>

## ⚽️ 트러블 슈팅

2024-12-03 18:20 UTC, Kyxxn requested changes
고생하셨습니다 !!!!!
로직 많이 겹쳐서 충돌 많이 났을텐데 고생하셨습니다 !!!!!!
밑에 수정할 부분들 코멘트 남겨뒀습니당

2024-12-03 18:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +    let audioPlayTimeLabel: UILabel = {
P2 여기 private 키워드만 붙여주시면 감사하겠습니당

2024-12-03 18:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +//        backgroundView.layer.borderColor = UIColor.baseBackground.cgColor
P2 불필요한 주석도 제거하면 좋을 거 같아요

2024-12-03 18:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +final public class MHAudioPlayerView: UIView {
P1 
public 제거하고, extension에 있는 메소드도 Public 제거 해주시면 감사하겠습니다 !

P3
7번 줄 개행 제거해주시면 감사하겠습니당

2024-12-03 18:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +    nonisolated public func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
P1 public

2024-12-03 18:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +            MHPolaroidPhotoView()
P1
제 똥이긴 한데 여기 `MHVideoView()`로 바꿔주실 수 있나요 ??

2024-12-03 18:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/ReadPage/View/ReadPageViewController.swift
> +            description in
저는 이전 버전이 더 좋아보이는데
후자가 나으신가용 ? (단순 궁금증입니다)

2024-12-03 18:20 UTC, Kyxxn commented on MemorialHouse/MHApplication/MHApplication/Resource/Info.plist
> +	<true/>
P1
제거하기로 결정했습니다 !!

2024-12-03 18:27 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +    let audioPlayTimeLabel: UILabel = {
GOOD😊

2024-12-03 18:27 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +//        backgroundView.layer.borderColor = UIColor.baseBackground.cgColor
GOOD😊

2024-12-03 18:27 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +final public class MHAudioPlayerView: UIView {
GOOD😊

2024-12-03 18:27 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +    nonisolated public func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
GOOD😊

2024-12-03 18:27 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +            MHPolaroidPhotoView()
GOOD😊

2024-12-03 18:27 UTC, yuncheol-AHN commented on MemorialHouse/MHApplication/MHApplication/Resource/Info.plist
> +	<true/>
GOOD😊

2024-12-03 18:48 UTC, k2645 requested changes
오디오 만들어주시느라 정말 수고하셨습니다 .ᐟ.ᐟ 🙇🏻‍♀️

궁금한 사항들이랑 수정되면 좋을 것 같은 내용들 코멘트로 조금 남겨두었습니다 .ᐟ.ᐟ

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/View/CreateAudioViewController.swift
> +        print("URL: \(url)")
P2: print문은 지워주면 좋을 것 같습니당 !

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/View/CreateAudioViewController.swift
> +    }
P3: 개행 컨벤션이 일정하지 않은데 통일시켜주면 좋을 것 같습니다 !

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/View/CreateAudioViewController.swift
> +                }
P1: 이쪽 혹시 Test 해보셨을까요?? 아마 requestRecordPermission 후행 클로저에 `Sendable` 붙이지 않으면 앱이 런타임 시점에 죽을 것 같습니다 ~

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +    }
P2: 해당 부분은 사용될 일은 없지만 만약을 위해 하단 url과 동일하게 메서드를 채워줘야할 것 같습니다 ! 약간 required init같은 느낌?

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +                }
P1: else문엔 어떤 처리가 들어가야하나요?

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +        }
P2: 애니메이션이 0초만에 일어나는 것이라면 애니메이션을 넣어야할 필요 있나요? 혹시 어떤 애니메이션때문에 해당 코드를 작성해주신 건가요?

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +        let width = ceil(Float(audioPlayer.currentTime) / Float(audioPlayer.duration) * Float(299))
P3: 299라는 숫자는 무엇을 의미하는 숫자인가요?

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +            }
P2: 해당 로직이 어떤 로직인지 잘 이해가 가지 않습니다.. 혹시 설명해주실 수 있으신가요?

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/ViewModel/CreateAudioViewModel.swift
> +    private let completion: (MediaDescription?) -> Void
P3: completion 핸들러는 보통 VC에 있었던 것 같은데, ViewModel에 completion이 있게 된 경위?가 궁금합니다 !

2024-12-03 18:48 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +        }
P2: 해당 메서드를 생성한건 좋은데 사용되지 않는 것 같습니다 .ᐟ.ᐟ 위 코드들을 해당 메서드를 활용하도록 변경해주면 좋을 것 같네용 !

2024-12-03 18:55 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/View/CreateAudioViewController.swift
> +        print("URL: \(url)")
GOOD😊

2024-12-03 18:58 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/View/CreateAudioViewController.swift
> +                }
```
AVAudioSession.sharedInstance().requestRecordPermission { @Sendable granted  in
    Task { @MainActor in
        if !granted {
            self.present(alert, animated: true, completion: nil)
        }
    }
}
```
이게 맞을까요? 테스트는 아직...

2024-12-03 19:01 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +    }
AVAduioPlayer Object 생성자 중 매개변수를 Data로 받는 부분이 없어서 조금 애매한데 Logger라도 찍는게 나을까요?

2024-12-03 19:12 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +        }
테스트해보니 필요 없을 거 같아요

2024-12-03 19:12 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +                }
제거했습니다!

2024-12-03 19:12 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Player/View/MHAudioPlayerView.swift
> +            }
오디오 플레이 테스트할 때 사용되었던 건데 지웠습니다.

2024-12-03 19:14 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditBook/View/EditPageCell.swift
> +        }
필요 없는 거 같아 지웠습니다.

2024-12-03 23:11 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/View/CreateAudioViewController.swift
> +                }
16.4기기로 테스트해봤었는데 잘 됐었습니다!

2024-12-04 00:19 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/Audio/ViewModel/CreateAudioViewModel.swift
> +    private let completion: (MediaDescription?) -> Void
VC에서 input(화면 닫히는 이벤트들)을 ViewModel에 보내면 ViewModel이 알아서 수행하도록 하고자 했습니다.

2024-12-04 00:41 UTC, Kyxxn approved these changes
고생하셨습니다 〰️

2024-12-04 00:41 UTC, k2645 approved these changes
수고하셨습니당 ~.ᐟ.ᐟ

2024-12-04 00:47 UTC, iceHood approved these changes
너무 고생하셨습니다...ㅠㅠㅠㅠ

2024-12-04 01:08 UTC, merged