MHLabel 커스텀 구현 (= 온글잎 베리려원 폰트 적용된 Label)
boostcampwm-2024/iOS10-MemorialHouse pull request #15
Opened 2024-11-05 15:20 UTC by Kyxxn

## #️⃣ 연관된 이슈
#14 

<br>

## 📝 작업 내용

- 온글잎 베리려원 폰트 적용된 커스텀 MHLabel 구현

<br>

## 📒 리뷰 노트

사용 예시입니다
``` swift
let label1 = MHLabel(labelText: "집주인 출판소1")
let label2 = MHLabel(labelText: "집주인 출판소2", color: .white)
let label3 = MHLabel(labelText: "집주인 출판소3", alignment: .right, color: .white)
```

<br>

## ⚽️ 트러블 슈팅

1. `온글잎 베리려원.ttf`을 Xcode에 넣는다고 되는게 아니라 info.plist에 `Fonts provided by application`로 넣어줘야 함
2. 한글로 된 "온글잎 베리려원.ttf"를 넣으니 Xcode가 이름을 `Ownglyph_BERRY_RW-Rg`로 바꿔버림 (ㅂㄷㅂㄷ)
아래 코드로 찾아서 해결했습니다.
	``` swift
    for family in UIFont.familyNames {
        print("Family: \(family)")
        for name in UIFont.fontNames(forFamilyName: family) {
            print("  \(name)")
        }
    }
	```

<br>

## 📸 스크린샷

<img width="1436" alt="스크린샷 2024-11-06 오전 12 15 51" src="https://github.com/user-attachments/assets/fa4ff2ea-9d6e-4dcc-bb1c-594575a62dd6">

2024-11-05 15:21 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +    ///   - color: 텍스트 색상. 기본값은 `UIColor.black`입니다.
이 주석 넣을지 말지,
넣는다면 이 위치에 둬도 되는지 피드백 부탁드립니당

2024-11-05 15:29 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +    }
모듈화를 해서 `required init`을 저희가 자주 사용할 것 같은데,
fatalError로 두기는 조금 그렇고 아래 두 개가 떠오릅니당

- fatalError에 @available(*, unavailable) 붙이고 냅두기
- @available(*, unavailable) 붙이지 말고 매번 디폴트로 구현해주기

뭐가 나은 거 같나요 ??
다른 방법 있으면 알려주셔도 좋을거 같습니다 !

2024-11-05 15:41 UTC, k2645 requested changes
첫 개인 PR이네용.ᐟ.ᐟ 수고하셨숩니다 .ᐟ.ᐟ 👍👍

2024-11-05 15:41 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +    @available(*, unavailable)
P2: 해당 어트리뷰러는 사용하지 않겠다는 뜻이었던 것 같은데, required 내부를 그냥 fatalError로 둬도 되지 않을까요?? 아니면 이 어트리뷰터는 없애도 될 것 같다고 생각합니다.

2024-11-05 15:41 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +    ///   - color: 텍스트 색상. 기본값은 `UIColor.black`입니다.
이렇게하면 `MHLable` 만들때 `init` 부분의 설명 글이 같이 나왔던것 같은데, 맞다면 저는 해당 주석이 좋은 것 같습니다 .ᐟ.ᐟ 엇 근데 13번째 줄은 없애야할 것 같습니다.

2024-11-05 15:41 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +        // 폰트 설정
P3: 위 생성자 부분에서 이미 설명이 나와있기 때문에 해당 주석은 없어도 될 것 같습니다. (54, 61번줄도 마찬가지입니다)

2024-11-05 15:41 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +        guard let font = UIFont(name: "Ownglyph_BERRY_RW-Rg", size: 25) else { return }
P2: 폰트의 이름을 `String`으로 바로 넣는 것에 대해 어떻게 생각하시나요? `MHLabel`이 아니더라도 해당 폰트는 앱 전반적인 부분에서 사용될 것 같은데 따로 Font의 `extension`를 만들어도 좋을 것 같습니다 !

2024-11-05 15:41 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +        let range = NSRange(location: 0, length: attributedString.length)
P2: align이나 color는 `UILabel`의 기본 프로퍼티를 사용해도 될 것 같은데, `AttributeString`을 사용하신 이유가 궁금합니다 .ᐟ.ᐟ

2024-11-05 15:41 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +        super.init(frame: frame)
P1: Text의 크기도 파라미터도 들어가야하지 않을까요??

2024-11-05 15:43 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +    }
제 개인적인 의견은 JK님께서 말씀해주셨던 2번째 방법이 좋을 것 같다는 생각입니다...ᐟ.ᐟ

2024-11-05 15:48 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +        super.init(frame: frame)
수정해씁니다!

2024-11-05 15:52 UTC, iceHood approved these changes
코드 잘봤습니다! 늦은 시간 고생 많으셨습니다,,, ㅎㅎ

2024-11-05 15:52 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +    ///   - color: 텍스트 색상. 기본값은 `UIColor.black`입니다.
기본값 때문에 도움말을 같이 적은걸까요? 저도 괜찮다고 생각합니다!

2024-11-05 15:52 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +    private var color: UIColor
P2. 혹시 이미 있는 UILabel 속성들을 사용하시지 않는 이유가 있으신가요?

2024-11-05 15:52 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +        // 폰트 설정
P3: 저는 읽기 좋았습니다 ㅋㅋㅋ헿

2024-11-05 15:56 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +        let range = NSRange(location: 0, length: attributedString.length)
원래 글자 간격 조절 때문에 AttributeString 사용했었는데,
우리 디자인에는 필요없을 것 같아 제거해놓고 그대로 사용하고 있었네용
UILabel 요소들로 바꾸겠습니다 !

2024-11-05 15:56 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +    }
> 제 개인적인 의견은 JK님께서 말씀해주셨던 2번째 방법이 좋을 것 같다는 생각입니다...ᐟ.ᐟ

[동의 합니다]

2024-11-05 15:57 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +    private var color: UIColor
위에 영현님 코멘트에 작성했는데, 글자 간격 조절 때문에 AttributeString 사용했었습니다..! (였던 것)
UILabel로 바꿀게용

2024-11-05 16:09 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHLabel.swift
> +        guard let font = UIFont(name: "Ownglyph_BERRY_RW-Rg", size: 25) else { return }
이런 느낌 말씀하시는 건가요 ??

``` swift
extension UIFont {
    static let 온글잎_베리려원 = "Ownglyph_BERRY_RW-Rg"
}
UIFont(name: UIFont.온글잎_베리려원, size: size)

```

2024-11-06 03:18 UTC, closed without merging

2024-11-06 10:05 UTC, Kyxxn commented
PR 닫은 사유
: 내부에서 따로 처리하는 게 없음에도
서브클래싱 할 필요가 없다고 판단하여 UILabel에 편의 생성자를 추가하기로 하였음