커스텀 앨범 생성
boostcampwm-2024/iOS10-MemorialHouse pull request #27
Opened 2024-11-07 13:56 UTC by k2645

## #️⃣ 연관된 이슈

- #19 

<br>

## 📝 작업 내용

- 앨범 & 카메라 접근 권한 Description 설정
- 커스텀 앨범 생성
- 카메라 접근 및 찍은 사진 활용

<br>

## 📒 리뷰 노트

CustomAlbum을 사용하기 위해서는 해당 VC을 부르기 전 아래 코드와 같이 앨범과 카메라에 대한 접근 권한을 확인한 후 접근해야합니다.

```swift
switch PHPhotoLibrary.authorizationStatus(for: .readWrite) {
case .notDetermined:
    PHPhotoLibrary.requestAuthorization(for: .readWrite) { status in
        switch status {
        case .authorized, .limited:
            self.presentAlbumViewController()
        case .denied:
            print("denied")
        default:
            print("그 밖의 권한이 부여 되었습니다.")
        }
    }
case .limited, .authorized:
    self.presentAlbumViewController()
case .restricted, .denied:
    print("권한이 없습니다.")
default:
    break
}
```

<br>

## ⚽️ 트러블 슈팅

### 1. 권한 설정

![image](https://github.com/user-attachments/assets/91ef58be-273c-457b-96a4-8febde4eb378)

info.plist에서 이미지 및 카메라 권한 Description을 설정해주지 않은 상태로 사용자의 앨범이나 카메라에 접근하려고 하면 위와 같은 에러가 발생합니다.

`Target` → `Info` → `Privacy - Photo Library Usage Description`, `Privacy - Camera Usage Description` 
두 key를 생성하고 경고 문구를 작성해줘야합니다.

이때, 권한에 대한 설명을 충분히 해주지 않으면 앱 배포를 할 때 리젝을 당할 수 있으니 자세히 설명해주는 것이 좋습니다 ^0^

### 2. CollectionView의 Cell 밖으로 Image가 벗어나는 이슈

커스텀 앨범은 굉장히 간단한 기본 Grid 형태의 CollectionView이고 각각의 cell은 `ImageView` 하나만을 가지고 있는 구조였다.

`PHAsset`을 사용하여 image를 사용자의 앨범에서 가져오고 그 이미지를 cell에 넣어주기만 하면 되는 간단한 작업이었는데, 아래 사진과 같이 image가 Cell을 벗어나는 이슈가 발생했다.

|시뮬레이터 스크린샷|뷰 Hierachy|
|:-:|:-:|
|<img width=230 src="https://github.com/user-attachments/assets/b951e1c1-eda1-4281-91d6-eec8c4c624a4">|<img width=300 src="https://github.com/user-attachments/assets/86f32459-2993-413f-b6f5-5e0940ed4a9c">|

이상한 점은 뷰의 hierachy를 찍어보면 또 잘 나온다는 점이었다....

cell 혹은 cell 내부의 imageView 크기가 잘못되었나 하고 LLDB를 활용하여 디버깅을 해봐도 아래와 같이 정사각형 형태로 잘 나왔다.

<img width=500 src="https://github.com/user-attachments/assets/e9d56bb0-ac6b-4238-b575-2494e07d35ce">

열심히 claud를 사용해보았지만 다 이상한 이야기만 해주고...

결국 cell의 imageView에서 `clipsToBounds` 프로퍼티를 `true`로 해줌으로써 해결할 수 있었다 .ᐟ.ᐟ 

<br>

## 📸 스크린샷

|앨범|앨범 및 카메라 접근 GIF|
|:-:|:-:|
|<img width=300 src="https://github.com/user-attachments/assets/0e7aede8-b886-45f9-aec5-f2a5e53ea47a">|<img width=300 src="https://github.com/user-attachments/assets/ca62d8b4-d719-4275-8f50-105558da2952">|

2024-11-07 14:59 UTC, Kyxxn requested changes
고생하셨습니다 !!!
자잘한 코멘트 및 질문은 아래에 남겨뒀습니다 !

2024-11-07 14:59 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +    }
P2
`required init`따로 구현해주신 이유가 있나요 ??

2024-11-07 14:59 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumCollectionViewCell.swift
> +    static let id = "CustomAlbumCollectionViewCell"
P2
`id`라고 줄여쓰지말고, `identifier`라고 적는 건 어떤가요 ?

2024-11-07 14:59 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumCollectionViewCell.swift
> +    static let id = "CustomAlbumCollectionViewCell"
P1
아래 Extension으로 처리하는 건 어떤까요 ?
휴먼 에러를 방지할 수 있을 것 같습니다

``` swift
extension UICollectionViewCell {
    static var identifier: String {
        String(describing: self)
    }
}
```

2024-11-07 14:59 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +    ) -> UICollectionViewCell {
P3
Delegate와 DataSource 메소드 선언 부를 모두 80~83처럼 인덴트를 가지는 건 어떨까요 ?

2024-11-07 14:59 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +extension CustomAlbumViewController: UICollectionViewDelegate, UICollectionViewDataSource {
P3
`extension UICollectionViewDelegate, UICollectionViewDataSource`을 한 번에 하지말고
각각 나누고 관련된 메소드 끼리 묶는 건 어떨까요 ?

2024-11-07 14:59 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +        fetchOptions.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: false)]
P3
이 옵션의 역할이 궁금합니다
생성된 날짜 최신 순으로 앨범을 정렬해서 보여주는 걸까요 ?!

2024-11-07 15:55 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +        fetchOptions.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: false)]
정확합니다.ᐟ.ᐟ 앨범에서 사진을 가져올 때 사진이 생성된 날짜 순으로 불러오게 되는 옵션입니다 .ᐟ.ᐟ

2024-11-08 01:26 UTC, iceHood requested changes
고생 많으셨습니다! 👍  👍  👍  👍  👍  👍  👍

2024-11-08 01:26 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumCollectionViewCell.swift
> +    static let id = "CustomAlbumCollectionViewCell"
저는 "다 좋습니다~"

2024-11-08 01:26 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumCollectionViewCell.swift
> +    static let id = "CustomAlbumCollectionViewCell"
> P1 아래 Extension으로 처리하는 건 어떤까요 ? 휴먼 에러를 방지할 수 있을 것 같습니다
> 
> ```swift
> extension UICollectionViewCell {
>     static var identifier: String {
>         String(describing: self)
>     }
> }
> ```

오 좋네요!

2024-11-08 01:26 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +    }()
P2. lazy를 사용하신 이유가 있나요?
```swift
private let collection = UICollectionView()

func configureCollectionView() {
  let flow = UICollectionViewFlowLayout()
  collection.collectionViewLayout = flow
}
```
lazy를 안쓰고 요렇게 할 수 있을 것도 같아서요!

2024-11-08 08:39 UTC, yuncheol-AHN approved these changes
고생하셨습니다 ~~ 늦어서 죄송해유🐯

2024-11-08 10:55 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +    }
지워야하는 코드인데 깜빡했습니다 .ᐟ.ᐟ 바로 수정하겠습니다 .ᐟ.ᐟ

2024-11-08 11:05 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +extension CustomAlbumViewController: UICollectionViewDelegate, UICollectionViewDataSource {
수정했습니다 !

2024-11-08 11:07 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +    }()
`CollectionView`를 선언할 때 저렇게 layout을 지정해주지 않고 인스턴스를 생성하게되면 `fatalError`가 발생하면서 앱이 터지게 됩니다 ㅠㅠ 위와 같은 이유로 해당 경우에는 불가피하게 `lazy`를 사용하게 되었습니다..

2024-11-08 11:07 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/CustomAlbumViewController.swift
> +            print("카메라에 접근할 수 없습니다.")
수정했습니다 .ᐟ.ᐟ

2024-11-08 11:51 UTC, iceHood approved these changes
고생 많으셨어요!!

2024-11-08 14:45 UTC, Kyxxn approved these changes
고생하셨습니다 〰️

2024-11-08 14:46 UTC, merged