앱 최초 실행 로직 (Layout X)
boostcampwm-2024/iOS10-MemorialHouse pull request #43
Opened 2024-11-10 13:16 UTC by yuncheol-AHN

## #️⃣ 연관된 이슈
- #41 

<br>

## 📝 작업 내용

- register view controller에서 기록소 이름을 입력받아 home view controller로 이동
- 이름을 입력하지 않은 경우 alert
- homeviewcontroller로 이동 후 뒤로가기 잠금

<br>

## 📸 스크린샷

저장소 입력 없이 <다음> 버튼 누르는 경우 alert

<img src="https://github.com/user-attachments/assets/733263db-23fb-43be-91af-ce41b083fbf2" width="320" height="640"></img>

저장소 입력 후 HomeViewController로 이동

![Simulator Screen Recording - iPhone 16 - 2024-11-10 at 22 10 17](https://github.com/user-attachments/assets/fdd068a0-f5ee-4eae-8dd4-0c592b6144ad)

UserDefaults가 존재하는 상황에서는 바로 HomeViewController로 이동

![Simulator Screen Recording - iPhone 16 - 2024-11-10 at 22 14 35](https://github.com/user-attachments/assets/84221216-9d99-461e-8715-c7380b138333)

2024-11-10 13:32 UTC, k2645 requested changes
정말 수고 많으셨습니당 ~~.ᐟ.ᐟ 읽어보고 리뷰 남겨두었습니다 !

2024-11-10 13:32 UTC, k2645 commented on MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
> +        let initController: UIViewController
P2: init이라는 축약어보다는 rootViewController나 initialViewController와 같은 단어를 사용하는게 저희 컨벤션에 더 잘 맞을 것 같습니다 !

2024-11-10 13:32 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
P2: - Mark 주석으로 프로퍼티나 생성자 부분, 메서드들을 구분해주면 좋을 것 같습니다 .ᐟ.ᐟ

2024-11-10 13:32 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +            userDefaults.set(houseName, forKey: "houseName")
P1: SceneDelegate에서도 사용되는 String값이니 외부에 Constant 값으로 한 번 변수화해주면 좋을 것 같습니다 .ᐟ.ᐟ 이렇게 String 값을 넣으면 휴먼에러가 발생할 수 도 있을 것 같아용..

2024-11-10 13:32 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +                self?.showAlert()
P2: 정확한 로직에 대해 이야기해본건 아니었지만 textField가 비어있을 경우 alert를 띄우기보단 다음 버튼을 비활성화 시키는건 어떨까요??

2024-11-10 13:58 UTC, iceHood approved these changes
고생하셨습니다!!! < 대 대 윤 철 대 대 >

2024-11-10 13:58 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +        registerButton.layer.cornerRadius = registerButtonFontSize
P3. (혹시 또 구현하고 계실까봐 말씀드립니다...) 배경 넣는 로직 따로 구현해 두었습니다! 나중에 UIView extension으로 embededInDefaultBackground 사용해주시면 될 것같아요!

2024-11-10 14:41 UTC, yuncheol-AHN commented on MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
> +        let initController: UIViewController
동의합니다!
rootViewController가 좀 더 당기긴 했지만, window?.rootViewController와 헷갈릴 수 있을 거 같아 initialViewController로 수정했습니다.

2024-11-10 14:45 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
MARK 습관이 안들었었는데 이번 프로젝트를 기회삼아서 습관 들여볼게요 ~

2024-11-10 15:01 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
mark 주석 snippet 만들어놓으면 편합니당 ~~ ㅎㅅㅎ

2024-11-10 15:24 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +            userDefaults.set(houseName, forKey: "houseName")
오홍 조아효~~

2024-11-10 15:38 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +            userDefaults.set(houseName, forKey: "houseName")
키에 대한 문자열은 첫글자 대문자여도 되지 않을까요 ??

2024-11-10 15:40 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +                self?.showAlert()
저도 이게 좋을 거 같습니다..!!

2024-11-10 16:11 UTC, Kyxxn requested changes
고생하셨습니다 윤철님 !!
제 의견 및 다른 분들 코멘트에 추가 의견 남겨두었습니다 ~!

2024-11-10 16:11 UTC, Kyxxn commented on MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
> +        let navigationController = UINavigationController(rootViewController: initController)
P3
이건 가독성이 별로일까요..?!

``` suggestion
let initialViewController = UserDefaults.standard.object(forKey: "houseName") == nil
? RegisterViewController()
: HomeViewController()

let navigationController = UINavigationController(rootViewController: initialViewController)
```

2024-11-10 16:11 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +        let registerButton = UIButton()
P2
UIButton에 type을 안 주신 이유가 있으신가용 ?

2024-11-10 16:11 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +        registerButton.layer.borderColor = #colorLiteral(red: 0.7019607843, green: 0.1490196078, blue: 0.1176470588, alpha: 1)
P1
혹시 저희 컬러 리터럴 쓰나요 ..?!
Assets에 넣어두고 사용하는 건 어떨까요 ?

2024-11-10 16:11 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +        view.addSubview(registerTextField)
P2
1. 현재 코드에 Public 생성자가 없는데 RegisterViewController가 SceneDelegate에서 생성이 되던가요 ??!
2. `MARK: -`만 나눠주시면 될 거 같습니다 ! (평소에 안 써보셨다고 하신 걸 봤는데, 다른 코드들 보면 힌트 얻으실 수 있을 것 같습니다 !)

2024-11-10 16:29 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +        registerButton.layer.cornerRadius = registerButtonFontSize
정현님 테스트 해보았는데, 제꺼 버튼 높이가 24인데 embededInDefaultBackground의 radius가 17로 24/2 보다 커서 테두리가 이질감이 조금 생기네요! 다른 곳에서 배경이 필요하면 적용시켜볼게요 !!

2024-11-10 16:38 UTC, yuncheol-AHN commented on MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
> +        let navigationController = UINavigationController(rootViewController: initController)
좋은 거 같아요 ! 수정했습니다 ~

2024-11-10 16:41 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +        let registerButton = UIButton()
type이 있는줄 몰랐네요 ㅎㅎ
default 값을 인자로 주도록 수정했습니다!

2024-11-10 16:53 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +        view.addSubview(registerTextField)
1. UIViewController에 init이 구현되어 있어서 생성이 되는 것 같아요!
2. 참고해서 수정했습니다 ~~

2024-11-10 17:29 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +            userDefaults.set(houseName, forKey: "houseName")
enum 타입으로 담았습니다 !

2024-11-10 17:32 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +        view.addSubview(registerTextField)
오! 뷰컨은 Public Init 필요없군요
하나 배워갑니다 !

2024-11-10 17:32 UTC, Kyxxn approved these changes
고생하셨습니다 ~!~!

2024-11-10 17:34 UTC, Kyxxn commented on MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
> +
P3
혹시 여기 개행 들어가있나용 ?? 있다면 없애도 좋을 거 같습니다 !

2024-11-10 23:18 UTC, iceHood requested changes
늦은 밤 고생하셨읍니다!! Etag관련해서 댓글 달았읍니다!

2024-11-10 23:18 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +}
P2. tag가 꼭 필요한가요? == 연산자로 대체할 수 있을 것같아서요!, 그리고 textfield가 하나만 쓰인다면 바로 empty인지만 확인해도 되지 않을까하는 생각입니다,,,

2024-11-11 00:57 UTC, k2645 approved these changes
전반적으로 윤철님 코드가 개행이 많이 들어가있는 것 같네용 .ᐟ.ᐟ 저도 개인적으론 개행을 넣으면 가독성이 좋아진다고 생각하긴 하지만 다른 분들의 코드와 일관성이 살짝 떨어져보일 수 있을 것 같아요 .. 괜찮으시다면 다른분들의 코드를 살짝 참고해서 개행을 조금 줄여보는 것도 좋을 것 같습니당 ...ᐟ.ᐟ 

너무 수고 많으셨습니다 🥹

2024-11-11 00:57 UTC, k2645 commented on MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
> +        : HomeViewController()
P3: 삼항연산자가 이렇게 내려쓰여진게 어색한 것 같아요.. 처음보는 스타일인 것 같네용.. 혹시 if 조건문을 사용하지 않으신 이유가 있으신걸까욥..??

2024-11-11 00:57 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +
P3: 각자의 코드 스타일인 것 같긴 하지만,, mark 주석 아래 개행은 없애는게 다른 분들과 통일감을 주는 코드가 될 수 있을 것 같아요 .ᐟ.ᐟ (아래 mark 주석들도 포함입니당 ㅎㅅㅎ)

2024-11-11 05:55 UTC, Kyxxn commented on MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
> +        : HomeViewController()
저 부분 제가 제의를 드렸었는데,
삼항 연산자는 swift에서 저렇게 쓰더라구요!
다른 분들 보시기에 가독성 별로인 거 같으면 기존 걸로 되돌려도 되긴 합니다

저는 if else보다 저게 가독성이 더 좋은데,
@iceHood 정현님은 어떠신가요?

2024-11-11 06:30 UTC, iceHood commented on MemorialHouse/MHApplication/MHApplication/Source/App/SceneDelegate.swift
> +        : HomeViewController()
사실 저는 코드 이해만 되면 장땡이다파라서 ㅋㅋㅋ
두분의 염원을 합쳐서 아래와같이 작성했습니다.
```swift
let initialViewController = if UserDefaults.standard.object(forKey: Constant.houseName) == nil {
      RegisterViewController()
    } else {
      HomeViewController()
    }
```

2024-11-11 15:32 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +
애플 라이브러리나 프레임워크에서 간격을 줘서 그렇게 했는데 통일하는게 맞겠네요!

2024-11-11 15:33 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Register/RegisterViewController.swift
> +}
혹시 TextField가 추가될지 몰라서 저렇게 해두었는데, 정현님 말씀도 맞는 것 같아요.

2024-11-11 15:39 UTC, Kyxxn commented on MemorialHouse/MHFoundation/MHFoundation/Constant/Constant.swift
> +}
Constant로 빼지말고, 아래처럼 UserDefaults에 확장으로 키 값을 관리하면 어떨까요 ?
된다면 파일명은 UserDefaults+Key가 좋을 거 같습니다

``` suggestion
extension UserDefaults {
    public static let houseName = "houseName"
}
```

2024-11-11 16:02 UTC, merged