BookCover 엔티티 & MHBook 뷰 구현
boostcampwm-2024/iOS10-MemorialHouse pull request #47
Opened 2024-11-11 19:14 UTC by Kyxxn

## #️⃣ 연관된 이슈
- #46 

<br>

## 📝 작업 내용

- BookCover 엔티티 완성
- MHBook 뷰 구현

<br>

## 📒 리뷰 노트

- BookCover 엔티티
	- 피그잼의 BookCover와 조금 다를 수 있습니다..!
	- favorite 같은 프로퍼티는 쓰이지 않아, 정말 MHBook에만 필요한 것만 넣었습니다
	- BookType의 경우 열거형은 Domain에 두되, UIImage에 대한 연산 프로퍼티가 있으면 좋을 것 같아
	Presentation 단에서 확장하여 구현했습니다.

- MHBook 뷰
	- 컨테이너 뷰 안에 아래의 내용을 넣었습니다
		- 책 겉면 (대영현 디자인)
		- 책 제목
		- 대상 이미지
		- 유저 출판소 이름
	- 대상에 대한 사진의 contentMode를 뭘로 할 지 고민했는데,
	우리 앱의 경우 사진 선택할 때 자르기 기능이 주어지니 scaleToFill로 정했습니다 ! (맞는지 모르겠네요)

<br>

## 📸 스크린샷

|scaleAspectFit|scaleAspectFill|scaleToFill (얘로 결정했습니다)|
|----|----|----|
|<img src="https://github.com/user-attachments/assets/2bb8084f-0ea1-45ab-8c51-71478d8188ef">|<img src="https://github.com/user-attachments/assets/cb9225a3-ff3a-4769-b79e-692483ebc2d3">|<img src="https://github.com/user-attachments/assets/1a10bb7d-572a-4f3b-acb9-b474e2e7fab5">|

2024-11-11 19:20 UTC, Kyxxn reviewed
Collection Flow는 따로 올리기로 했습니다
MHBook만 먼저 올렸는데, 모델부터 해서 아직 부족한 게 많네요
리뷰하면서 고쳐나가겠습니다 ~~

오늘 무지성 회의만 했는데.. 굿나잇입니다 여러분 🌙

2024-11-11 19:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +    }
CollectionViewCell에서 사용되어야 하기 때문에 다음과 같이 configure로 설정해주었습니다

CollectionViewDatasource에서 Reuse 되면, cell.configure(with: 모델) 호출
cell.configure(with:)에서 해당 메소드를 호출하게끔 할 생각이긴 합니다..!

2024-11-11 19:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +}
Domain에 있는 모델이지만 Presentation에서 위처럼 연산 프로퍼티 접근이 가능하면 용이할 것 같아 추가해봤습니다
괜찮다면..? 해당 코드가 어디 위치에 있는게 좋을까요

2024-11-11 19:58 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +}
[추가] 아래 코드는 필수로 구현해줘야 했습니다!
책이 안 보이면 강제종료 되는게 맞다 판단하여 fatalError 그대로 냅뒀는데 다른 아이디어 있으신 분 있으면 알려주세욥
``` swift
        @unknown default:
            fatalError("등록되지 않은 책 색상입니다.")
        }
```

2024-11-12 00:35 UTC, iceHood requested changes
효준님 늦은시간 고생 많으셨습니다 ㅠㅠ 🙇‍♂️  이렇게 Book도 만들어주시고.... 감사히 잘 쓰겠습니다?!헿... 정말 고생 많으셨어요...

2024-11-12 01:52 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +        bookImageView.fillSuperview()
인정합니다 !
컨테이너 뷰 제거해서 다시 올렸습니당

2024-11-12 05:16 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +}
제 생각에도 default 수행 안될 거 같은데,
다른 모듈에 있는 걸 extension으로 열어서 그런지 `@unknown default`를 해주지 않으면 에러가 발생했습니다 !

2024-11-12 05:23 UTC, k2645 approved these changes
수고많으셨습니당 .ᐟ.ᐟ 

scaleToFill보다 scaleAspectFill을 하고 imageView의 크기만큼 clipsToBounds 해주면 더 좋을 것 같습니다 .ᐟ.ᐟ (비율이 안맞는게 조금 외관상 보기가.. 안좋은 느낌..?)

2024-11-12 05:23 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +        bookImageView.image = bookCover.bookType.image
저는 여기서 case별로 나눠서 image를 적용해줘도 된다.. 생각합니당.. 뭔가 model의 extension에 computed property가 들어가는게 어색..한 것 같다..? 는 의견입니당..

2024-11-12 05:23 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +        addSubview(publisherLabel)
P3;

```suggestion
[bookImageView, 
 titleLabel, 
 targetImageView,
 publisherLabel].forEach { addSubView($0) }
```

요건 어떤가욥??

2024-11-12 05:25 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomain/Entity/BookCover.swift
> +}
UIImage에 대한 건데 Color라는 이름을 쓰기가 애매했습니다..!
아래처럼 사용돼도 괜찮나요 ? (개인적) 전 Type이 나을 거 같은데 어떠신가용

``` swift
extension BookColor {
	var image: UIImage {
		return .pinkColor
	}
}
```

2024-11-12 05:57 UTC, yuncheol-AHN approved these changes
고생하셨슴 당당 ~~

2024-11-12 05:57 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +}
`@frozen`을 사용해 타입을 고정시켜도 `@unknown default`를 작성해야하는 문제가 발생할까요?

2024-11-12 06:04 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomain/Entity/BookCover.swift
> +}
인정합니다 수정할게욥

2024-11-12 06:13 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +}
컴파일러가 띄워준 에러에 자동완성 Fix가 @.unkown default였는데
그냥 늘 쓰던 default였군요, 제거하고 default로 수정했습니다 !!

2024-11-12 06:31 UTC, iceHood approved these changes
고생 많으셨읍니다!! 계속 달려보죵

2024-11-12 06:31 UTC, k2645 approved these changes
너무너무 수고 많으셨습니다 ~.ᐟ.ᐟ 👍👍👍

2024-11-12 06:46 UTC, yuncheol-AHN approved these changes
대장님 고생 많으셨어요❕❕

2024-11-12 07:01 UTC, merged