홈 화면 레이아웃 구현 (with CollectionViewFlowLayout)
boostcampwm-2024/iOS10-MemorialHouse pull request #51
Opened 2024-11-12 11:34 UTC by Kyxxn

## #️⃣ 연관된 이슈
- #14 

<br>

## 📝 작업 내용

- UICollectionView와 FlowLayout을 통한 홈 화면 레이아웃 그리기
- 홈 우측 하단 `추억 만들기` 버튼 생성
	- 누를 시 책 생성 화면으로 이동
	- 딱 이동만 됨, 아직 네비게이션 바에 대한 처리는 잘 안 되어 있음

<br>

## ⏰ 작업시간

|예상 시간|실제 걸린 시간|
|:-:|:-:|
|평균: 5.3 (본인: 8)|5|

<br>

## 📒 리뷰 노트

- FlowLayout에서 셀을 어떻게 보여줄 지 고민을 많이 해봤는데, 아이폰 16프로와 SE 3세대에서 실행해보며 조정함..
	- FlowLayout 잡을 때 UIEdgeInsets을 쓸지, 컬렉션뷰에 오토레이아웃 잡을 지 등등 아직 미흡하네요
- 우측 하단의 `추억 만들기` 버튼에 임의로 쉐도우를 넣었는데 어떤가요 ..??
	<img width="142" alt="스크린샷 2024-11-12 오후 8 33 01" src="https://github.com/user-attachments/assets/3f678b83-ff1b-41f7-a2e1-fefeb14ad638">
	<img width="144" alt="스크린샷 2024-11-12 오후 8 33 09" src="https://github.com/user-attachments/assets/cca7ca7d-511a-41d7-a2d3-5493b2bc42a3">
	<img width="146" alt="스크린샷 2024-11-12 오후 8 33 16" src="https://github.com/user-attachments/assets/cc26def2-e4ba-4f13-8bdb-68c4aab856b7">

<br>

## 📸 스크린샷 & 영상

### 영상
|컬렉션 뷰 레이아웃|책 생성화면으로 이동|
|:-:|:-:|
|![홈레이아웃 구현](https://github.com/user-attachments/assets/3c9f9834-7a8c-4714-83e9-43e683d495f4)|![홈- 책생성 화면이동](https://github.com/user-attachments/assets/6f300ea0-3dd6-447e-9e04-75fdb063f7bf)|

### 스크린샷
|iPhone 16 Pro|iPhone SE 3rd generation|
|:-:|:-:|
|![스크린샷 2024-11-12 시간: 19 10 15](https://github.com/user-attachments/assets/b06fefda-006e-48eb-975c-9496892d48ac)|![스크린샷 2024-11-12 시간: 19 12 35](https://github.com/user-attachments/assets/7561266d-89ed-4967-87bb-791bf3414246)|

2024-11-12 11:53 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +        flowLayout.scrollDirection = .vertical
MHBookCover에서도 TargetImageView를 width height로 잡았는데,
여기서도 width height로 잡는게 뭔가 레이아웃을 잘 못 잡고 있다는 생각이 드는데 이 구조가 괜찮은 건가요 ??

2024-11-12 12:02 UTC, k2645 requested changes
너무너무 수고 많으셨습니당 .ᐟ.ᐟ 플로팅 버튼에 그림자 준 건 너무 좋은 것 같아요 .ᐟ.ᐟ 효카소 해야겠는데용

2024-11-12 12:02 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewModel.swift
> +    let houseName: String
P1: 해당 변수는 private 처리해줘야할 것 같습니다 .ᐟ.ᐟ

2024-11-12 12:22 UTC, iceHood requested changes
국굳입니당 
ᕦ(ò_óˇ)ᕤ

2024-11-12 12:22 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +        flowLayout.scrollDirection = .vertical
그러면, 음 BookCover는 오토레이아웃으로 잡고 TargetImageView는 width height로 잡는 것은 어떤가요?

2024-11-12 12:22 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +    }()
P2. 스샷보니까 floating button이 cell을 가리는 것같은데 혹시 조정이 가능할까요?

2024-11-12 12:22 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +        navigationController?.navigationBar.isHidden = true
왠지 홈뷰가 왔다 갔다 할일이 많아서 여기에 하신 것같아요!

2024-11-12 12:44 UTC, yuncheol-AHN approved these changes
고생하셨습니다 ~~

2024-11-12 12:44 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +        flowLayout.itemSize = .init(width: cellSize, height: 210)
P3
cellSize 대신 cellWidth는 어떨지 조심스럽게 제안드립니다.
hegiht에 대한 부분도 변수로 하면 일관성이 있을 거 같습니다.

2024-11-12 13:28 UTC, k2645 reviewed
효준님 추가로 이미지를 봤을 때 책 하단에 더보기 버튼(...) 이게 먼가 비율이.. 피그마랑 살짝 다른 것 같아서 이것 한 번 봐주시면 너무너무 감사드리겠습니당 🙇🏻‍♀️🙇🏻‍♀️

2024-11-12 14:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBookCover.swift
> +    }
옹 좋네요 알겠습니다 !

2024-11-12 14:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +    private let bookCoverMakeFloatingButton: UIButton = {
인정합니다 수정할게요

2024-11-12 14:21 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +        navigationController?.navigationBar.isHidden = true
맞습니당 책 만들고 다시 돌아오면 다시 네비게이션 바가 생겨있어서
viewWillAppear에 두었습니다

2024-11-12 14:23 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +        flowLayout.itemSize = .init(width: cellSize, height: 210)
인정합니당 수정할게요 !!

2024-11-12 14:26 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +    }()
마지막 셀 안 가리게 스크롤을 내릴 때는 플로팅 버튼이 내려가고
스크롤 올릴 때 플로팅 버튼이 생기게 해보겠습니당 ~

2024-11-13 15:53 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +    }()
다음 PR로 올리겠습니당

2024-11-13 23:09 UTC, iceHood approved these changes
너무 공생 많으셨읍니다!! 오늘도 화이팅,,
╰(*´︶`*)╯♡

2024-11-14 01:45 UTC, k2645 approved these changes
HomeViewModel의 리뷰들이 아직 반영되지 않은 것 같습니다 .ᐟ.ᐟ 일단 Approve는 드렸는데, 해당 파일 리뷰 확인해주시고 반영해주신 후에 Merge해주시면 감사하겠습니다 .ᐟ.ᐟ

2024-11-14 01:54 UTC, yuncheol-AHN approved these changes
열정맨 ~ 고생많으셨습니다 !!!

2024-11-14 06:09 UTC, merged