새로운 책 만들기 - 프리뷰와 입력뷰 연결, 색 버튼 효과, 임시로직 추가
boostcampwm-2024/iOS10-MemorialHouse pull request #54
Opened 2024-11-12 18:05 UTC by iceHood

## #️⃣ 연관된 이슈
- #45 

<br>

## ⏰ 작업 시간

|예상 시간|실제 걸린 시간|
|:-:|:-:|
|3.5(5)|8|

로직 자체는 3.5인데 버튼 효과에 시간을 갈아 넣었다는 사실...

## 📝 작업 내용

- ViewModel 만들기
- 입력에 따른 프리뷰 업데이트
- 버튼 그림자 효과 넣기
<br>

## 📸 스크린샷

https://github.com/user-attachments/assets/4b910e06-6e5e-459c-8a5f-8eaca72e3db6

<br>

## 📒 리뷰 노트

아 프리뷰 업데이트 시간은 오래걸리는 것이 아닌 일부로 좀 지연했습니다...
뭔가 한글자마다 바뀌는 게 맞나 싶어서 (사실 바뀌어도 될것같기도?)
<br>

## ⚽️ 트러블 슈팅

### 그림자효과 넣기...

그림자를 넣는데 CALayer때문에 에러가 계속 났다.
아니, 처음에는 CALayer에러인줄도 몰랐다.
아래 처럼 이상하게 에러가 발생했기 때문이다.

![image](https://github.com/user-attachments/assets/6d803a3a-e4d3-455f-aa18-78684b858c16)

그래서 왜 발생하지.. 하면서 이것저것 ViewModel이 문젠가....
컴바인이 문젠가...
하..... 왜지
하다가 CALayer를 딱 지우니까 오류가 안나서 여기서 뭔가 있다는 것을 느꼈다. (문제 발생 5시간만에)

그래서 `removeFromSuperlayer` 에서 발생한 것을 알았다.

레이어를 하나만 들고 그것을 계속 재활용하는 방식으로 개선하여 해결했다.

2024-11-12 18:26 UTC, Kyxxn approved these changes
고생하셨습니다..!!
이번 주 내내 초과근무 하시는 군요
화이팅입니다 Steve Lim,

2024-11-12 18:26 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +        return mHBook
P3
변수명 mH로 하신 이유가 있나용??

2024-11-12 18:26 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +    private func configureNavigationBar() {
오 네비게이션 바 좋네용
정현님 걸로 쓰면 될 거 같습니다

2024-11-12 18:26 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +            self?.colorButtonInnerShadow.removeFromSuperlayer()
이게 그 inner shadow 문제의 코드인가용 ㅋㅋㅋㅋㅋ

2024-11-12 18:26 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +        titleLabel.setTrailing(anchor: trailingAnchor, constant: 17)
P2
지금 제가 올려둔 PR에서 MHBook이 아닌 MHBookCover로 바꿨습니당
머지 전에 참고만 하시면 될 것 같아요!

2024-11-12 18:26 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +            .debounce(for: .seconds(0.3), scheduler: DispatchQueue.main)
제가 지금 폰드리뷰라 그런데,
이 debounce는 메인 스레드에서 0.3초 딜레이 걸어주는 건가요??

추가로 현재 클래스에 @.Published viewModel을 하셨던데, 나중에 로직이 바뀔 예정인건가용?

2024-11-12 18:27 UTC, Kyxxn commented
아 추가로 저는 텍스트 필드의 한글자 한글자 당
바로 보이는게 ux적으로 더 좋아보이긴 합니다!

2024-11-12 22:57 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +        return mHBook
ㅋㅋㅋ bookView로 해야겠네요 그냥 귀찮음 이슈였습니당 핳 좋읍니다

2024-11-12 23:03 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +            .debounce(for: .seconds(0.3), scheduler: DispatchQueue.main)
아 debounce는 메인스레드를 멈추지는 않고, 변경 이벤트를 감지한 후 0.3초 기다렸다가 요청이 없으면 반영하고, 아니면 최신 이벤트를 받고 다시 0.3초 기다리는 기능이라고 합니다?! 
(+) 로직의 경우 저희 바인딩 방식 정확히 정하면 그것에 맞춰서 수정할께욤!

2024-11-12 23:05 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +            self?.colorButtonInnerShadow.removeFromSuperlayer()
ㅠㅠ 디버깅이 친절하지 않아서 혼났네요...

2024-11-12 23:07 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Design/MHBook.swift
> +        titleLabel.setTrailing(anchor: trailingAnchor, constant: 17)
죻읍니다!

2024-11-13 00:23 UTC, yuncheol-AHN approved these changes
정현님 늦은 시간까지 고생 많으셨습니다 ~!
모르는 개념 제외하고 코드 잘 이해되는 거 같아요!❕

출근 화이팅입니다💼

2024-11-13 01:26 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +            .debounce(for: .seconds(0.3), scheduler: DispatchQueue.main)
오호 감사합니닷

2024-11-13 02:40 UTC, k2645 requested changes
정말 수고 많으셨습니다 .ᐟ.ᐟ 답변을 받고 싶은 부분들이 몇몇 있어 일단 request changes로 남겨뒀어요 ~ 근데 inner shadow.. 정말 고생 많으셨겠군요..... 못난 디자이너를 둔...죄...

2024-11-13 02:40 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewModel.swift
> +struct BookCreationViewModel {
P2: ViewModel을 struct로 만들어주셨는데 다른 곳들과 다르게 하신 이유가 있으신가요?? 뭔가 제가 느끼기에 해당 구조체는 MVVM의 ViewModel이라기보다는 BookCreation이라는 하나의 view에서 사용되는 model같다는 생각이 듭니다 !

2024-11-13 02:40 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +            .debounce(for: .seconds(0.3), scheduler: DispatchQueue.main)
P3: 보통 debounce는 사용자가 버튼같은 걸 빠르게 연타했을때, 그걸 모두 감지하는걸 방지하기위해 사용되는 걸로 알고있습니당.ᐟ.ᐟ 뷰 모델과 바인딩을 하는데 debounce를 넣어주신 이유가 무엇인지 궁금합니다 .ᐟ.ᐟ

2024-11-13 02:40 UTC, k2645 commented
> 아 추가로 저는 텍스트 필드의 한글자 한글자 당 바로 보이는게 ux적으로 더 좋아보이긴 합니다!

저도 동의합니다 .ᐟ.ᐟ

2024-11-13 05:04 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +        configureViewModelBinding()
화면에 안보이면 바인딩을 중지하기 위해서입니다!

2024-11-13 06:47 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +            .debounce(for: .seconds(0.3), scheduler: DispatchQueue.main)
키보드 입력이 많이 되거나 이미지 바꾸는 게 여러번 되면 부담될까봐 이렇게 하긴 했었는데 debounce 안 써도 될것같군요!

2024-11-13 06:53 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewModel.swift
> +struct BookCreationViewModel {
일단, 만들어진 viewmodel이 영현님 자료밖에 없기도 했고, 제가 (input - output 구조 라고 할까요?)여기에 익숙하지 않았습니다. 또한 딱히 아직 viewmodel에 대해 제대로 정해진 바도 없기도 해서 그냥 당장 구현하는데에 필요할 정도로만 했습니다. 또한 자료형  밖에 없는 게 아직 usecase, entity도 코드상으로 정해지지 않기도 해서 입니다.

2024-11-13 07:25 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewModel.swift
> +struct BookCreationViewModel {
결론 == 일단 구현하자 느낌으로 막 만듦

2024-11-13 07:56 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +            .debounce(for: .seconds(0.3), scheduler: DispatchQueue.main)
아하 그렇다면 키보드 입력부분이나 이미지를 바꾸는 부분에서 debounce를 넣어주는게 적절할 것 같네용 .ᐟ.ᐟ

2024-11-14 01:55 UTC, k2645 approved these changes
너무 수고 많으셨습니당 .ᐟ.ᐟ 🥹👍

2024-11-14 01:55 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +        )
P3: 임시 값들은 이후에 수정할 수 있으니 TODO를 남겨두면 좋을 것 같습니당 !

2024-11-14 07:02 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +        )
좋습니다! 이미지는 todo 남기고, publisher는 UserDefault에서 가져왔읍니다!

2024-11-14 07:04 UTC, merged