홈에서 카테고리 드랍다운 클릭 시 컨텐츠 내용물에 따라 Custom Detent Sheet 보이기
boostcampwm-2024/iOS10-MemorialHouse pull request #65
Opened 2024-11-19 15:06 UTC by Kyxxn

## #️⃣ 연관된 이슈
- #63 

<br>

## ⏰ 작업 시간

|예상 시간|실제 걸린 시간|
|:-:|:-:|
|4.8h|5h|

## 📝 작업 내용

- 홈에서 카테고리 드랍다운 클릭 시 컨텐츠 내용물에 따라 Custom Detent Sheet 보이기
- UIBarItem에 대한 편의 생성자를 만들어 리팩토링함

<br>

## 📸 스크린샷

![CustomDetent](https://github.com/user-attachments/assets/baf1b058-a31c-4ae4-8be1-e10e6631bee5)

2024-11-19 15:10 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryTableViewCell.swift
> +    nonisolated static let height: CGFloat = 44
Category ViewModel에서 시트지의 높이 계산할 때
`셀 개수 * CategoryTableViewCell.height`로 연산을 하는데 MainActor 에러가 발생하더라구요,

여기는 레이스 컨디션 발생해도 상관없지 않나 싶어서 nonisolated를 붙였는데 맞는지 모르겠습니다..
사실 제가 nonisolated를 제대로 이해한 건지도 모르겠네요
훈수 부탁드립니다

2024-11-19 23:42 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryTableViewCell.swift
> +    nonisolated static let height: CGFloat = 44
변화가 없으니까 저는 괜찮다고 생각합니다!

2024-11-20 00:30 UTC, iceHood approved these changes
전체적으로 코드가 깔끔해서 읽기 좋았습니다!! 고생 많으셨어요!

2024-11-20 00:30 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewController.swift
> +
P3. TODO 달아주면 좋을 것같아요!

2024-11-20 00:30 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewController.swift
> +        }
P2. 전체, 즐겨찾기를 ViewModel에서 관리하지 않으신 이유가 있나요?

2024-11-20 01:55 UTC, k2645 requested changes
정말 수고 많으셨습니다 ~.ᐟ.ᐟ 네비게이션 바 편의생성자 만들어 놓은게 정말 편해보이네요 :)

2024-11-20 01:55 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryTableViewCell.swift
P3: TableViewCell도 Button과 마찬가지로 [cell configuration](https://developer.apple.com/documentation/uikit/uitableviewcell/3601058-defaultcontentconfiguration)이 있다는거 아시나용 ?? 저희 카테고리와 같이 기본적인 TableViewCell은 따로 커스텀 파일을 만들지 않아도 cell configuration을 사용하면 더 간단하게 구현 가능하답니당 ! 물론 당장 이걸 써라 .ᐟ.ᐟ 는 아니고 알아두시면 좋을 것 같아 코멘트 남겨드립니당 ~ 이거 관련해서 [zedd님 블로그](https://zeddios.tistory.com/1205)도 굉장히 잘 나와있어서 그거 읽어보시는 것도 추천드려용 ㅎㅎ

2024-11-20 01:55 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewController.swift
> +    }
P3: 해당 부분도 모두 폰트 사이즈가 22네용.. 다른 곳과 통일하기 위해서 17로 해주는 건 어떨까요..??

2024-11-20 01:55 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewController.swift
> +        }
동의합니당 ! 전체랑 즐겨찾기도 기본적인 카테고리이긴 하지만 viewModel에서 관리해줘야한다고 생각해용

2024-11-20 01:55 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewModel.swift
> +    }
P2: 해당 로직은 뷰의 데이터 관련 로직이라기 보단 뷰를 그리는? 뷰와 직접적으로 연관된 로직인 것 같아서 viewmodel에 있는게 어색해보입니다 ! 개인적으로 뷰모델은 뷰에 들어갈 데이터 관련 로직만 들어가야한다고 생각해서 해당 로직은 VC에 있는게 더 자연스러울 것 같다는 생각입니당

2024-11-20 01:55 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewModel.swift
> +        dummyData = ["집주인들", "가족", "친구", "동료", "기타"]
P3: 실제 develop 브랜치에 들어갈 파일에서는 확인용 dummy data는 제거해주시는게 좋을 것 같습니다 ! 그리고 TODO 추가해주시면 좋을 것 같아요 !

2024-11-20 01:55 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Extensions/UIBarButtonItem+Create.swift
> +    }
옹 너무 좋은데요 ?!?! 👍👍👍

2024-11-20 02:16 UTC, yuncheol-AHN approved these changes
밤 늦게까지 고생하셨습니다 ~⭐️

2024-11-20 02:16 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +            self?.present(navigationController, animated: true)
카테고리 시트에 언제 뎁스가 생기는지 궁금합니다!
navigation controller로 구현되어 있어서 여쭙니다

2024-11-20 02:19 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/BookCreation/BookCreationViewController.swift
> +            .font: UIFont.ownglyphBerry(size: 22),
엇 원래 17로 작업했는데,
지난 주 폰 빌드 실행했을 때 네비게이션 폰트가 너무 작다는 피드백을 받아서 17~25 중에 제일 적정한 22로 해두긴 했습니다
다시 17로 해둘까요 ??

2024-11-20 02:20 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryTableViewCell.swift
오 감사합니다!!
당연하게 커스텀 셀 쓰고 있었는데 굳이 싶긴 하네요
읽어보겠습니다 ~~

2024-11-20 02:22 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Category/CategoryViewController.swift
> +        }
인정합니다 수정하겠습니당

2024-11-20 02:28 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +            self?.present(navigationController, animated: true)
시트지에 보여질 '카테고리 뷰컨'에서 네비게이션을 설정해줘야 하는데,
Present 방식으로 시트지를 보이게 하기 위해서 카테고리 뷰컨을 새 네비게이션 컨트롤러로 감싸서 띄우도록 설정을 해줬습니다!

이거 말씀하신 게 혹시 맞나요..??
아니라면 말씀해주세용

2024-11-20 06:22 UTC, k2645 approved these changes
정말 수고 많으셨습니당 ~~

2024-11-20 06:22 UTC, merged