이미지 Crop 구현 및 TextField 위치 조정, CustomAlbum ViewModel 구조 리팩토링
boostcampwm-2024/iOS10-MemorialHouse pull request #66
Opened 2024-11-19 16:41 UTC by k2645

## #️⃣ 연관된 이슈

- #52 

<br>

## ⏰ 작업 시간

|예상 시간|실제 걸린 시간|
|:-:|:-:|
|6.5 (8)| 1n |

며칠.. 걸렸는데 정확한 시간은 모르겠숩니다.. 
다른 부가적인 기능들도 추가로 구현하느라 조금 더 걸린 것 같숩니다 ㅠ

## 📝 작업 내용

- 이미지 crop 구현
- 키보드에 따른 TextField 위치 조정
- CustomAlbum ViewModel 구조 리팩토링
- 사용자 앨범 사진 추가 및 삭제 observing

<br>

## 📸 스크린샷

|사용자 앨범 사진 추가 및 삭제 Observing|키보드에 따른 TextField 위치 조절|
|:-:|:-:|
|<img width=300 src="https://github.com/user-attachments/assets/1f19c146-3c4a-4f8a-9d63-9e629ba47537">|<img width=300 src="https://github.com/user-attachments/assets/4b4bfc16-6b95-4952-98d8-a7bba796326e">|

|이미지 Crop|
|:-:|
|<img width=300 src="https://github.com/user-attachments/assets/52357a79-0920-482b-a31b-f96aae9f569b">|

<br>

## ⚽️ 트러블 슈팅

### PanGesture + PinchGesture vs ScrollView

Crop을 하기 위해서 이미지 편집 페이지에서 이미지가 확대 및 축소 되어야했다. 이를 구현하기 위해 맨 처음 생각난게 바로 직접 UIImageView에 panGesture와 pinchGesture를 달고 그걸 조절하는 것이었다.

하지만 이미지가 원하는 뷰에서 벗어나면 안된다던지... 말로 설명하긴 복잡한 로직이 있었다 ㅠㅠ 그걸 하나하나 조절해주기 위해선 너무 복잡한 로직과 계산이 필요했고..중도 포기 하고싶었다..^0^

근데 다시 잘 생각해보니 ScrollView가 있었던 것 ;; 그냥 ScrollView 내부에 ImageView를 위치시키고 아래와 같이 어떤 뷰를 줌시킬지를 정해주면 줌인 줌아웃, 스크롤까지 한 번에 됐다..

```swift
extension EditPhotoViewController: UIScrollViewDelegate {
    func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return photoImageView
    }
}
```

물론 그렇다고 내부 로직이 크게 쉬워지진 않았지만 그래도 gesture를 두 개 한 번에 달면서 손가락 두 개로 gesture를 줄 때 끊기는 듯한 느낌이 드는 문제를 해결할 수 있었다.

2024-11-19 17:42 UTC, Kyxxn requested changes
잔다 해놓고 잡일 처리하느라 늦어진 김에 PR까지 달고 갑니다 ^ㅇ^

영현님의 주요 Crop 로직은 다 못 봤고,
코드 일관성 및 궁금증 위주로 코멘트 드렸습니다
자르기는 아침에 일어나서 다시 보겠습니다 ~!

2024-11-19 17:42 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
> +        output.receive(on: DispatchQueue.main)
P2 질문
메인 스레드에서 받는 이유가 있나요 ??
아래 구독 이벤트들에 대한 작업이 곧 뷰를 그리는 작업이라 그런 건가요 ??

2024-11-19 17:42 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
>              self.navigationController?.popViewController(animated: true)
P3
제가 이번에 올린 PR에 네비게이션 아이템 만드는 편의 생성자 Extension 추가해둬서
영현님이 보시기에 가독성 증가 필요 시 적용해보셔도 좋을 것 같습니다 !

2024-11-19 17:42 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
> +            print("카메라 권한 거부")
P3
아직 구현되지 않은 부분이라도 Logger 습관화하면 좋을 것 같습니다 !
혹은 print 지우고 올려도 좋겠네요

2024-11-19 17:42 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
> +        }
P2
`@unknown` 키워드 지워도 되지 않나요 ?
fatalError도 필수적인지 궁금합니다!

2024-11-19 17:42 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/CustomAlbumViewModel.swift
> +        case changedAssets(_ changes: PHFetchResultChangeDetails<PHAsset>)
P3
연관값 받는 부분에서 매개변수 앞에 _ 붙이는 게 나은가용 ??
8번 줄도 마찬가지 입니다!
(단순 질문) with, at, in .. 과 같은 와일드카드(?)를 써보는 건 어떨까요 ?

2024-11-19 17:42 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
>          navigationItem.rightBarButtonItem = rightBarButton
위와 마찬가지 입니다!

2024-11-19 17:42 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
> +    @objc private func keyboardWillAppear(_ notification: Notification) {
P3
저는 아래처럼 사용하곤 하는데,
아래와 같이 써보는 건 어떨까요 ?! (무시하셔도 됩니다)

``` suggestion
    @objc
    private func keyboardWillAppear(_ notification: Notification) {
```

2024-11-19 17:42 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
> +        return photoImageView
P3
return 제거하는 게 낫지 않을까용 ?

2024-11-19 17:43 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
> +    }
P2
아 추가로, 이 파일도 그렇고 아래 Edit도 그렇고
네비게이션바 설정을 viewWillAppear에서 해주시던데 이유가 있으신가요 ?

2024-11-19 23:27 UTC, iceHood approved these changes
굉장히 고생하셨습니다 !! 역시...역시...
ʅ（◞‿◟）ʃ

2024-11-19 23:27 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
> +    }
혹시 photoDidChanged가 어떤 경우에 호출되는지 알 수 있을까요?

2024-11-20 02:44 UTC, yuncheol-AHN approved these changes
늦은 시간까지 정말 고생하셨습니다 ~~~ 대 영 현 ⭐️
C. R. O. P.

2024-11-20 02:44 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/CustomAlbumViewModel.swift
> +            }
P3
클로저 매개변수로 하나의 이벤트를 전달받는다고 생각했는데 이벤트들이 전달되는 경우도 있나요?
이벤트가 case에 따라 하나만 전달되는게 맞다면 클로저 매개변수를 events -> event로 변경하는 건 어떤가요?

2024-11-20 04:08 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
> +        output.receive(on: DispatchQueue.main)
넵.ᐟ.ᐟ 맞습니다 .ᐟ.ᐟ

2024-11-20 04:09 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
>              self.navigationController?.popViewController(animated: true)
효준님 PR 머지되고 나서 다음 제 PR에서 수정하겠습니당 .ᐟ.ᐟ 효준님께서 만들어주신 편의 생성자 정말 좋은 것 같아요 .ᐟ.ᐟ

2024-11-20 04:12 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
> +        }
옹 xcode의 fix를 눌러서 나오는 코드를 그대로 놨네요 .. 
해당 switch문에 들어가는 모든 옵션들을 위에 구현해줘서 default 값이 나올 경우는 존재하지 않는게 맞습니다 ! 그래도 fatalError를 발생시키는건 극단적인 것 같네용 ! 해당 부분은 log를 찍는 형태로 수정하겠습니다 .ᐟ.ᐟ

2024-11-20 04:15 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/CustomAlbumViewModel.swift
> +        case changedAssets(_ changes: PHFetchResultChangeDetails<PHAsset>)
옹 좋은 것 같습니다 .ᐟ.ᐟ

2024-11-20 04:22 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
> +        return photoImageView
저희 한 줄의 경우 return은 생략하자는 컨벤션이 있었나요 ?-?

2024-11-20 04:24 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
> +    }
넵! 이미지 편집뷰와 커스텀 앨범뷰 사이의 화면전환이 일어날 때마다 NavigationBar의 appearance가 바뀌어야해서 viewWillAppear에 넣어줬습니다 !

2024-11-20 04:25 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/View/CustomAlbumViewController.swift
> +    }
위 함수는 커스텀 앨범이 아닌 사용자의 앨범에 변화(사진 추가 및 사진 삭제)가 일어날때 그걸 실시간으로 옵저빙하기 위해 있는 함수입니다 !
따라서 사용자 앨범에 새로운 사진이 추가되거나 삭제 등의 변화가 일어났을때 호춤됩니당!

2024-11-20 04:26 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/CustomAlbum/ViewModel/CustomAlbumViewModel.swift
> +            }
맞습니당 .ᐟ.ᐟ 수정하겠습니다 ~.ᐟ.ᐟ

2024-11-20 04:52 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/EditPhoto/EditPhotoViewController.swift
> +        return photoImageView
엇 아닙니다 !! 프로젝트 뒤져봤는데 뒤죽박죽이긴 하네용
넘어가도 좋을 거 같습니다 !

2024-11-20 04:53 UTC, Kyxxn approved these changes
고생하셨습니닷 !

2024-11-20 04:53 UTC, merged