Feature/filtering book
boostcampwm-2024/iOS10-MemorialHouse pull request #73
Opened 2024-11-24 14:15 UTC by Kyxxn

## #️⃣ 연관된 이슈

<br>

## ⏰ 작업 시간

|예상 시간|실제 걸린 시간|
|:-:|:-:|
|||

## 📝 작업 내용

<br>

## 📸 스크린샷

<br>

## 📒 리뷰 노트

<br>

## ⚽️ 트러블 슈팅

2024-11-24 23:04 UTC, Kyxxn reviewed
테스트 코드 환경 구축 & 테스트 2개 작성했더니 평소보다 파일 변화가 더 많아진 것 같습니다,,
다음부터 적게적게 올리겠습니다

Swift Testing을 진행해봤는데, 그 과정에서 알게된 내용 기술공유에 정리해두겠습니다
+ 아직 여러 태그를 비롯해서 Swift Testing을 잘 활용하고 있지 못하다는 생각이 드는데 더 공부해봐야겠네요.

2024-11-24 23:04 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentationTests/HomeViewModelTest.swift
> +        receivedOutputs.removeAll()
비워주지 않으면 위 테스트 메소드 `func test카테고리_선택시_해당_카테고리에_맞는_책들로_필터링한다()`에 의해 항상 실패하게 되는 것을 보고 추가해주었습니다

2024-11-25 02:01 UTC, iceHood approved these changes
주말을 불태운 당신께.... Cheers 🍷

2024-11-25 02:02 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomain.xcodeproj/project.pbxproj
인정합니다 바로 반영할게요

2024-11-25 02:17 UTC, k2645 requested changes
정말 수고 많으셨습니다 .ᐟ.ᐟ 코멘트 쫌쫌따리 남겨두었어용 ~

2024-11-25 02:17 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +            case .fetchedMemorialHouse:
P2: viewmodel이 memorial house를 프로퍼티로 가지고 있기보단 해당 output이 memorialHouse에 대한 값을 넘겨주는 방식이 조금 더 자연스러울 것 같다는 생각입니다 ! viewmodel의 프로퍼티에 view가 직접 접근하는 방식은 최대한 지양하는게 좋을 것 같습니당

2024-11-25 02:17 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentationTests/HomeViewModelTest.swift
> +    @MainActor
P3: test 코드에 mainactor가 붙은게 어색해 보이는데.. 이렇게 해주신 이유가 있으신가욥..?

2024-11-25 02:17 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentationTests/HomeViewModelTest.swift
> +        try await Task.sleep(nanoseconds: 500_000_000)
P3: 중단 시간을 두는 이유가 무엇인가요?

2024-11-25 02:34 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomain/UseCase/DefaultUserHouseUseCase.swift
> +}
?? 아하..! 멍청이슈..
수정하겠습니다

2024-11-25 02:38 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentationTests/HomeViewModelTest.swift
> +    @MainActor
HomeViewModel의 메소드들이 MainActor에서 동작하기 때문에
테스트 코드의 메소드들도 MainActor 키워드를 붙이지 않으면 에러가 발생했습니다 !
이번 PR은 사실 Actor 공부가 다 잘 안 돼서 비즈니스 로직에 중점을 두긴 했어요

2024-11-25 02:53 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentationTests/HomeViewModelTest.swift
> +        try await Task.sleep(nanoseconds: 500_000_000)
input output 스트림에서 비동기로 동작하니까 지연시간을 줘서 이벤트를 확실히 받을 수 있게 했습니다 !

2024-11-25 03:12 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomainTests/UserHouseUseCaseTest.swift
> +    @Test mutating func test유저하우스_엔티티모델_가져오기() async throws {
오 확인했습니다 우리 테스트의 test는 제거할게요 !!
그러면 `Swift Testing에서는 함수명에 test를 붙이지 않아도`라는 말씀이면 기존 XCTest에서는 접두사에 `test`를 필수적으로 하나요 ??

2024-11-25 03:17 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomainTests/UserHouseUseCaseTest.swift
> +    @Test mutating func test유저하우스_엔티티모델_가져오기() async throws {
참 우리 린트에 따라서 메소드 접두사의 첫 글자가 소문자가 아니면 에러가 발생해서 `test`를 붙였었습니다 !!
린트를 끄는 건 좋은 판단이 아니라 생각되는데, 어떻게 하면 좋을까요 ??

<img width="1049" alt="스크린샷 2024-11-25 오후 12 17 18" src="https://github.com/user-attachments/assets/cea21327-6451-4b36-872d-da47f088a36a">

2024-11-25 03:58 UTC, k2645 commented on MemorialHouse/MHDomain/MHDomainTests/UserHouseUseCaseTest.swift
> +    @Test mutating func test유저하우스_엔티티모델_가져오기() async throws {
움 제 생각은 솔직히 프로퍼티나 메서드 명은 다들 무조건 lowercase로 작성하시니까 린트를 끄는것도 괜찮다 생각하긴합니당.. 하지만 린트를 끄는게 좀 그렇다면 그냥 앞에 test를 붙여주는것도 좋아보입니다.ᐟ.ᐟ 

그리고 위 효준님 질문에 답변드리자면 XCTest에서는 메서드명 맨 앞에 test를 붙여줘야 컴파일러가 해당 메서드가 테스트 코드라는걸 인지한다고 알고있습니다.ᐟ.ᐟ 실제로 메서드 명에 test를 붙여주지않으면 좌측 마름모꼴 버튼이 뜨지 않는답니당..(이것때매 삽질해본 경헙 있을 유..😇)

2024-11-25 05:19 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomainTests/Stubs/StubMemorialHouseRepository.swift
> +public struct StubMemorialHouseRepository: MemorialHouseRepository {
인정합니다 까먹고 제거 안 했네요..!
수정하겠습니다 !!

2024-11-25 05:26 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomain/Entity/BookCover.swift
> +        favorite: Bool = false
반영했습니다 !

2024-11-25 05:34 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomainTests/UserHouseUseCaseTest.swift
> +    @Test mutating func test유저하우스_엔티티모델_가져오기() async throws {
오호 감사합니다 !! 마름모가 떴다 안 떴다 하던데 그 이유 때문이었군요..
그리고 린트는 저는 이대로 둬도 된다고 생각합니다 !

2024-11-25 05:36 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomainTests/UserHouseUseCaseTest.swift
> +    @Test mutating func test유저하우스_엔티티모델_가져오기() async throws {
MHDomain Test의 throws는 제거했습니다

2024-11-25 05:40 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +            case .fetchedMemorialHouse:
오.. 12있는 말씀이십니다
그러면 뷰컨이 프로퍼티로 들고있을 필요는 없고, 받아서 바로 UI 그리는데에만 쓰는 느낌으로 가는 건가요 ?

2024-11-25 05:45 UTC, Kyxxn commented on MemorialHouse/MHDomain/MHDomain/Entity/BookColor.swift
> +public enum BookColor: Sendable {
<img width="1053" alt="스크린샷 2024-11-25 오후 2 42 17" src="https://github.com/user-attachments/assets/5b413b38-8c50-491f-8b09-62844c38c17f">

붙이지 않으면 모델이 non-isolated 하다는 에러를 내뿜어서 일단 붙여둔 상태입니다..!

2024-11-25 05:51 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Home/HomeViewController.swift
> +            case .fetchedMemorialHouse:
넵넵 맞습니다 .ᐟ.ᐟ

2024-11-25 05:52 UTC, k2645 approved these changes
정말 너무너무 수고 많으셨습니다 🥹

2024-11-25 05:53 UTC, merged