Audio
boostcampwm-2024/iOS10-MemorialHouse pull request #88
Opened 2024-11-27 12:22 UTC by yuncheol-AHN

## #️⃣ 연관된 이슈

<br>

## ⏰ 작업 시간

|예상 시간|실제 걸린 시간|
|:-:|:-:|
|3.5|10+|

저는 왕 감자 입니다. 🥔🥔🥔

## 📝 작업 내용

- 오디오 세션 열기
- 세션을 통해 전달 받은 decibels을 meteringLevel로 변환
- 음성 데이터 FileManager를 통해 저장

<br>

## 📸 스크린샷

https://github.com/user-attachments/assets/fbecadb0-e1a3-48bb-82ae-fedb692d49ea

<br>

## 📒 리뷰 노트

- AVAudioSession을 통해 오디오세션을 실행(active)
- AVAudioRecorder를 통해 음성(데시벨)을 전달받는다.
-  데시벨은 (-0 ~ -160)까지의 값이고 -0이 큰 소리 -160이 무음이다. 이 때, AVAudioRecorder가 STOP 상태에서는 -160 값으로 유지되는데 일단 RECORD되면 웬만큼 조용하지 않아서는 -60보다 작은 값으로 잘 안내려간다. 
- 데시벨 값은 직관적인 파형으로 다가오지 않아서 튜닝(decibel -> metering level)을 조금 해줬습니다.
- AudioViewController를 생성할 때 생성된 UUID을 File Name으로하고 음성 파일 저장
- 취소 버튼을 누르면 해당 경로에 있는 오디오 파일 제거 (AVAudioRecorder를 Stop할 때 자동으로 파일이 저장되서 취소 버튼을 눌렀을 때 해당 파일을 제거해주는 방식으로 구현)

<br>

## ⚽️ 트러블 슈팅

### 런타임에 오토레이아웃이 조절되지 않는 문제

constraints를 deactivate해주고 다시 activate하는 방식으로 해결

```swift
NSLayoutConstraint.deactivate(audioButton.constraints)
audioButton.setWidthAndHeight(width: 48, height: 48)
audioButton.setCenter(view: audioButtonBackground)
NSLayoutConstraint.activate(audioButton.constraints)
```

2024-11-27 14:22 UTC, k2645 requested changes
정말 수고 많으셨습니당 .ᐟ.ᐟ 디자인도 음성 녹음도 뚝딱뚝딱 해주시는 당신은 대.윤.철.✨

2024-11-27 14:22 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +        let audioFileURL = documentDirectory.appendingPathComponent(fileName)
P2: 위 UUID 프로퍼티나 FileManager에 저장하는 코드등은 ViewModel로 따로 로직을 분리하는게 저희 아키텍처에 더 적절할 것 같습니당 !

2024-11-27 14:22 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +        downMeteringView.setWidthAndHeight(width: 300, height: volumeHalfHeight)
P2: 효준님께서 만들어두신 anchor 메서드를 사용하면 자동으로 `translatesAutoresizingMaskIntoConstraints`는 false처리를 해줍니다 ! 따라서 `translatesAutoresizingMaskIntoConstraints`를 false 처리해주는 코드들은 중복되는 코드임으로 삭제하면 좋을 것 같습니다 ~

2024-11-27 14:22 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +        NSLayoutConstraint.activate(audioButtonConstraints)
P3: 혹시 이 부분만 저희 Anchor 메서드를 사용하지 않은 이유가 있으실까요??

그리고 아래와 같이 배열을 `.activate()` 내부에 바로 넣어줘도 될 것 같습니당 ~

```suggestion
    audioButton.translatesAutoresizingMaskIntoConstraints = false
    NSLayoutConstraint.activate([
        audioButton.widthAnchor.constraint(equalToConstant: 48),
        audioButton.heightAnchor.constraint(equalToConstant: 48),
        audioButton.centerXAnchor.constraint(equalTo: audioButtonBackground.centerXAnchor),
        audioButton.centerYAnchor.constraint(equalTo: audioButtonBackground.centerYAnchor)
    ])
```

2024-11-27 14:22 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +                        message: "Please enable microphone access in Settings to use this feature.",
P3: 저희 앱의 기본 local이 한국어로 되어있으니 사용자 편의 측면에서? alert의 메세지도 한글로 하는게 더 좋을 것 같습니당

2024-11-27 14:23 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +        let audioFileURL = documentDirectory.appendingPathComponent(fileName)
아앗 ! 맞습니다 ~! 수정하도록 할게요!

2024-11-27 14:24 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +        downMeteringView.setWidthAndHeight(width: 300, height: volumeHalfHeight)
효준님 코드 사용안하고 constraints 수정하는 부분이 있을까해서 구현해두고 정리하려고했는데, 깜빡했네요 ㅠㅠ 수정하겠습니다 ~~

2024-11-27 14:25 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +        NSLayoutConstraint.activate(audioButtonConstraints)
수정하겠습니다 !!

2024-11-27 14:25 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +                        message: "Please enable microphone access in Settings to use this feature.",
I agree with you

2024-11-27 15:08 UTC, iceHood approved these changes
오디오.... 힘든 것을 해낸 당신은 대윤철... 너무 고생하셨습니다!

+) 약간 전체적인 P2라고 해야할까요? ViewModel연결이 다음과제가 될듯싶습니다 ㅎㅎ

2024-11-27 15:23 UTC, Kyxxn approved these changes
우리팀 걱정요소 중 하나였던 오디오를 이렇게 깔꼼하게..
고생하셨습니다 윤철님 ~~

2024-11-27 15:24 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +                        message: "Please enable microphone access in Settings to use this feature.",
Thank you ~ yun ~

2024-11-30 14:29 UTC, Kyxxn requested changes
고생하셨습니다 윤철님 ~!~!
변경할 사항들은 코멘트 남겨뒀어요 !!

2024-11-30 14:29 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewModel.swift
> +    // called in controller
P1
요 주석은 없어도 될 거 같습니당

2024-11-30 14:29 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewModel.swift
> +        try? FileManager.default.removeItem(at: audioTemporaryFileURL)
P1
try? 옵셔널 말고 try로 해서 throws에 걸릴 경우 catch에서 뷰컨트롤러에 실패했다고 send를 보내주면
유저 친화적인 로직이 될 수 있을 것 같습니다 !
이해가 잘 안 되면 홈 로직 보셔도 좋을 것 같아용

2024-11-30 14:29 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewModel.swift
> +        debugPrint("audio button tapped in view model")
P1
MHLogger.debug 쓰시면 됩니다 !!

2024-11-30 14:30 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewModel.swift
> +    // called in controller
앗 ㅋㅋ 공부하면서 적어둔건데 안지웠네요 ㅠ

2024-11-30 14:34 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewModel.swift
> +        debugPrint("audio button tapped in view model")
호옹 고치겠습니다 ~

2024-11-30 14:35 UTC, k2645 approved these changes
수고하셨습니당 .ᐟ.ᐟ 👍

2024-11-30 14:35 UTC, k2645 commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +                debugPrint("delete temporary audio file")
P2: 해당 부분은 output에 대한 로직이 따로 존재하지않는다면 굳이 output을 방출하지 않아도 되지않을까.. 싶습니다 ! 혹시 이후 이 부분에 추가적인 로직이 필요한 것이라면 TODO로 각각의 output에 대해 어떤 로직이 추가되어야할지 적어두는게 좋을 것 같습니다 ! 

추가로 아래 효준님 코멘트와 같이 여기도 MHLogger로 변경해주면 좋을 것 같아용

2024-11-30 14:36 UTC, Kyxxn commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewModel.swift
> +        try? FileManager.default.removeItem(at: audioTemporaryFileURL)
오옷 좋습니다 !!

2024-11-30 14:37 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +                debugPrint("delete temporary audio file")
todo 간단하게 작성할게요 ~

2024-11-30 14:56 UTC, iceHood approved these changes
고생하셨습니다 윤철님! 일부 궁금한 것들 댓글로 남겼습니다!_!

2024-11-30 14:56 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +        let audioFileURL = documentDirectory.appendingPathComponent(fileName)
P2. 이거 혹시 반영됐나요?

2024-11-30 14:56 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
P2. 이름관련해서 AudioViewController, AudionViewModel이면 추후에 저희가 보여질 뷰와 이름이 겹칠것같아서 AddAudio-- 나 EditAudio-- CreateAudio-- 등을 쓰는 것은 어떨까요?

2024-11-30 14:56 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +    private var timeTimer: Timer?
P3. timeTimer는 혹시 어떤 역할인가요? (이름만으로 파악하기 힘든 것같아요)

2024-11-30 14:56 UTC, iceHood commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewModel.swift
P3. 나중에 UseCase를 통해 파일 관련 로직을 위임하는 것도 좋을 것같습니다!

2024-11-30 15:26 UTC, closed without merging

2024-11-30 15:26 UTC, yuncheol-AHN commented
commit count issue

2024-11-30 15:39 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
> +    private var timeTimer: Timer?
레코딩 시간을 의미하는 것이였는데, 다시보니 이해가 잘 안되서 수정했습니다.

2024-11-30 15:41 UTC, yuncheol-AHN commented on MemorialHouse/MHPresentation/MHPresentation/Source/Audio/AudioViewController.swift
수정완!